/** Dev-only snapshot used on the 2nd Bright Data profiles poll. */
export const BRIGHTDATA_SECOND_POLL_PROFILES: Record<string, unknown>[] = [
  {
    about: 'Core Skills: Core Java, Advanced Java (Multithreading), Java SE (JavaFX, Swing)…',
    avatar:
      'https://media.licdn.com/dms/image/v2/D5603AQHxJrNJY-Y9tQ/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1694494933069?e=2147483647&v=beta&t=6WHiQiyhjjY-Is_4zNGLcWF5wCUvJR9ErRhrkxutirM',
    city: 'Kochi, Kerala, India',
    country_code: 'IN',
    current_company: {
      company_id: 'tata-consultancy-services',
      name: 'Tata Consultancy Services',
      title: null,
    },
    current_company_name: 'Tata Consultancy Services',
    first_name: 'Anandhu',
    id: 'anandhu-arjunan-74a577146',
    last_name: 'Arjunan',
    linkedin_id: 'anandhu-arjunan-74a577146',
    location: 'Kochi',
    name: 'Anandhu Arjunan',
    position: 'Java Developer at Tata Consultancy Services',
    url: 'https://in.linkedin.com/in/anandhu-arjunan-74a577146',
    input_url: 'https://in.linkedin.com/in/anandhu-arjunan-74a577146',
    experience: [
      {
        company: 'Tata Consultancy Services',
        title: 'System Engineer',
        end_date: 'Present',
      },
    ],
  },
  {
    about: 'I am Geethu Francis. Experienced Java Developer with 3 years of expertise in designing…',
    avatar:
      'https://media.licdn.com/dms/image/v2/D5603AQHRgQpodtGXew/profile-displayphoto-shrink_200_200/B56ZVxbVILHsAY-/0/1741364746641?e=2147483647&v=beta&t=d-yZIWB5aYXMbw-Hjg52ekI21cmznlt5v8u1Hmgp1C8',
    city: 'Kochi, Kerala, India',
    country_code: 'IN',
    current_company: {
      company_id: 'pearldatadirect',
      name: 'Pearl Data Direct',
      title: null,
    },
    current_company_name: 'Pearl Data Direct',
    first_name: 'GEETHU',
    id: 'geethu-francis-04529b241',
    last_name: 'FRANCIS',
    linkedin_id: 'geethu-francis',
    location: 'Kochi',
    name: 'GEETHU FRANCIS',
    position:
      'Java Developer | Microservices | Springboot developer | REST apis | Restful web services | Backend Developer | Java Backend Developer',
    url: 'https://www.linkedin.com/in/geethu-francis-04529b241',
    input_url: 'https://www.linkedin.com/in/geethu-francis-04529b241',
    experience: [{ company: 'nishkaiv Solutions LLP', title: 'Spring Boot Developer', end_date: 'Present' }],
  },
  {
    about: 'I am a Java Developer with 5 years of experience in building scalable web applications…',
    avatar:
      'https://media.licdn.com/dms/image/v2/D5603AQHDypMin7DD9w/profile-displayphoto-scale_200_200/B56Z1iVxgQHMAY-/0/1775471370017?e=2147483647&v=beta&t=pxHafDwC4rS75sxhUd8JUebd9MZR9sLIxK74QDH41BM',
    city: 'Trivandrum, Kerala, India',
    country_code: 'IN',
    current_company: {
      company_id: 'ul-technology-solution',
      name: 'UL Technology Solutions',
      title: null,
    },
    current_company_name: 'UL Technology Solutions',
    first_name: 'AJAY',
    id: 'ajay-rohan-m-5a7b941a2',
    last_name: 'ROHAN M',
    linkedin_id: 'ajay-rohan-m-5a7b941a2',
    location: 'Trivandrum',
    name: 'AJAY ROHAN M',
    position: 'Software Engineer | Java Developer | Spring Boot | Angular | Android Studio | MySQL | Postgresql',
    url: 'https://www.linkedin.com/in/ajay-rohan-m-5a7b941a2/',
    input_url: 'https://www.linkedin.com/in/ajay-rohan-m-5a7b941a2/',
    experience: [{ company: 'UL Technology Solutions', title: 'UL Technology Solutions' }],
  },
  {
    about: 'Lead Engineer at Quest Global with 9 years of experience in Spring Boot, Microservices…',
    avatar: 'https://static.licdn.com/aero-v1/sc/h/9c8pery4andzj6ohjkjp54ma2',
    city: 'Chavakkad, Kerala, India',
    country_code: 'IN',
    current_company: { company_id: 'quest-global', name: 'Quest Global', title: null },
    current_company_name: 'Quest Global',
    first_name: 'Christeena',
    id: 'christeena-john-a65280101',
    last_name: 'John',
    linkedin_id: 'christeena-john-a65280101',
    location: 'Chavakkad',
    name: 'Christeena John',
    position:
      'Oracle Certified Java Developer | SAP Certified Developer | Spring Boot | Microservices | Magnolia CMS',
    url: 'https://www.linkedin.com/in/christeena-john-a65280101',
    input_url: 'https://www.linkedin.com/in/christeena-john-a65280101',
    experience: [
      { company: 'Quest Global', title: 'Lead Engineer', end_date: 'Present' },
    ],
  },
  {
    about: 'IT professional with around 4 years of experience in the areas of Java Full Stack…',
    avatar:
      'https://media.licdn.com/dms/image/v2/D5603AQGr5vW-YwZ1vQ/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1722238557309?e=2147483647&v=beta&t=zAI2iiNNei9tQLbdkbDdZRl9GCkArhkBRglnxLlMsRc',
    city: 'Trivandrum, Kerala, India',
    country_code: 'IN',
    current_company: { company_id: 'ustglobal', name: 'UST', title: null },
    current_company_name: 'UST',
    first_name: 'Gautham',
    id: 'gautham-krishna-j-l-4499a01b8',
    last_name: 'Krishna J L',
    linkedin_id: 'gautham-krishna-j-l-4499a01b8',
    location: 'Trivandrum',
    name: 'Gautham Krishna J L',
    position: 'Software Developer || Java Developer',
    url: 'https://www.linkedin.com/in/gautham-krishna-j-l-4499a01b8',
    input_url: 'https://www.linkedin.com/in/gautham-krishna-j-l-4499a01b8',
    experience: [{ company: 'UST', title: 'UST' }],
  },
  {
    about: 'Experienced Software Developer | Java Enthusiast | Spring Boot Specialist',
    avatar:
      'https://media.licdn.com/dms/image/v2/D5603AQETlH8WDuk80Q/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1728098767224?e=2147483647&v=beta&t=3V_tzVE6l74gcLbnv0QhO9y2UKxbigBuScSjOtKLHl0',
    city: 'Kochi, Kerala, India',
    country_code: 'IN',
    current_company: { company_id: 'ibssoftware', name: 'IBS Software', title: null },
    current_company_name: 'IBS Software',
    first_name: 'Hiba',
    id: 'hiba-naser-990b03244',
    last_name: 'Naser',
    linkedin_id: 'hiba-naser-990b03244',
    location: 'Kochi',
    name: 'Hiba Naser',
    position: 'Java Developer',
    url: 'https://www.linkedin.com/in/hiba-naser-990b03244',
    input_url: 'https://www.linkedin.com/in/hiba-naser-990b03244',
    experience: [{ company: 'IBS Software', title: 'Lead Product Engineer' }],
  },
  {
    about: 'Passionate Software Developer . Experienced in Full Stack Java Developer intership and…',
    avatar:
      'https://media.licdn.com/dms/image/v2/D5603AQGkvWCrPSp7ng/profile-displayphoto-scale_200_200/B56ZoAtHpHJwAY-/0/1760948421229?e=2147483647&v=beta&t=haC7hp0NVNAYq18D9PZ1b64dzgdAUXeyXi7-QZNmrAY',
    city: 'Trivandrum, Kerala, India',
    country_code: 'IN',
    current_company: { company_id: 'buddygouk', name: 'Orbule', title: null },
    current_company_name: 'Orbule',
    first_name: 'Abhijith',
    id: 'abhijith-jose-585ba4226',
    last_name: 'jose',
    linkedin_id: 'abjoseabhi',
    location: 'Trivandrum',
    name: 'Abhijith jose',
    position:
      'Software developer -1 C++ || Full Stack Java Developer || SQL || Core Java || HTML and CSS || J2EE || Jira || Ext js',
    url: 'https://linkedin.com/in/abhijith-jose-585ba4226',
    input_url: 'https://linkedin.com/in/abhijith-jose-585ba4226',
    experience: [{ company: 'UST', title: 'Software Developer' }],
  },
];
